#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# This script audits the specified project in the IDA service, and reports if any
# data is older than the configured or specified age limit.
#
# The script directly queries the database tables and filesystems, and it is
# not necessary for Apache/Nextcloud/IDA to be running in order to execute this
# script; only the database needs to be running.
# --------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT project [ max_age_in_days ] [ --json-output ] [ --no-user-email ] [ --quiet ]
       $SCRIPT -h
"

# --------------------------------------------------------------------------------

INIT_FILE=`dirname "$(realpath $0)"`/lib/init_audit_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting."
    exit 1
fi

#DEBUG="true" # TEMP HACK

#--------------------------------------------------------------------------------

MAX_AGE=`echo "$2" | sed -e 's/[^0-9]//g'`

if [ -z "$MAX_AGE" ]; then
    MAX_AGE=365
fi

JSON_OUTPUT=`echo "$*"   | grep -- "--json-output"`
NO_USER_EMAIL=`echo "$*" | grep -- "--no-user-email"`
QUIET=`echo "$*"         | grep -- "--quiet"`

#--------------------------------------------------------------------------------

if [ "$DEBUG" = "true" ]; then
    echo "ROOT:       $ROOT"          >&2
    echo "PROJECT:    $PROJECT"       >&2
    echo "START:      $START"         >&2
    echo "MAX_AGE:    $MAX_AGE"       >&2
    echo "JSON OUT:   $JSON_OUTPUT"   >&2
    echo "NO EMAIL:   $NO_USER_EMAIL" >&2
    echo "QUIET:      $QUIET"         >&2
fi

if [ "$QUIET" ]; then
    QUIET="true"
else
    QUIET="false"
fi

#--------------------------------------------------------------------------------

if [ ! -d "$PROJECT_STORAGE_OC_DATA_ROOT" ]; then
    errorExit "The specified project ${PROJECT} does not exist"
fi

LOG_ROOT=`dirname "$(realpath $LOG)"`
YEAR=`date -u +"%Y"`
MONTH=`date -u +"%m"`
REPORT_ROOT="${LOG_ROOT}/old_data"
REPORT="${LOG_ROOT}/old_data/${YEAR}/${MONTH}/${START}_${PROJECT}.json"

mkdir -p $REPORT_ROOT/$YEAR/$MONTH 2>/dev/null

#--------------------------------------------------------------------------------

MESSAGE="Project ${PROJECT} has files which have been stored in IDA for longer than ${MAX_AGE} days and which haven't yet been included in any dataset.

IDA's Terms of Use specify that files stored in IDA are intended to be included in one or more published dataset descriptions, even if the data itself is not openly public.

You have two options:

1. Include the data in one or more datasets using the Fairdata services: https://www.fairdata.fi/en/fairdata-quick-guide/

2. Arrange for a special extension: If, for some reason, you cannot yet include your data as part of any published dataset, please inform us and specify how much time you expect to need (e.g. in months). With a legitimate reason, we can grant you more time for preparing the data.

We ask you to please use IDA according to its intended purpose. Disregarding IDA's Terms of Use can lead to termination of your use rights.

If you have no need or intention to publish your data as part of one or more datasets, we ask you to move the data to an alternative storage solution such as Allas (https://research.csc.fi/-/allas) or a service provided by your home organization.

If you require assistance with the data publication process, or you need a list of the files in question that are still unpublished, our support team is here to help. Please contact servicedesk@csc.fi

Best regards,

The IDA team

**

Projektillasi ${PROJECT} on tiedostoja, jotka ovat olleet tallennettuina IDA-palveluun yli ${MAX_AGE} päivää eikä niitä ole vielä kuvailtu ja julkaistu.

IDAan tallennettu data tulee jäädyttää, kuvailla ja julkaista osana tutkimusaineistoa Etsimeen, vaikka itse data ei olisikaan julkisesti saatavilla.

Sinulla on kaksi vaihtoehtoa:

1. Julkaise datasi osana yhtä tai useampaa tutkimusaineistoa: [https://www.fairdata.fi/en/fairdata-quick-guide/]

2. Mikäli jostain syystä et voi vielä julkaista dataasi, ilmoita meille siitä ja kerro paljonko aikaa tarvitset (esim. montako kuukautta). Voimme perustellusta syystä antaa sinulle lisää aikaa datan valmisteluun.

Pyydämme käyttämään IDAa sen käyttöehtojen ja tarkoituksen mukaisesti. IDAn käyttöehtojen laiminlyönti voi johtaa käyttöoikeuksien päättämiseen.

Jos sinulla ei ole tarvetta tai aikomusta kuvailla ja julkaista dataasi, pyydämme sinua siirtämään tiedostosi vaihtoehtoiseen tallennusratkaisuun, kuten Altaaseen ([https://research.csc.fi/-/allas]) tai tiedustelemaan eri vaihtoehdoista kotiorganisaatioltasi.

Jos tarvitset apua datan julkaisuprosessissa tai haluat listan kyseisistä tiedostoista joita ei ole vielä julkaistu, autamme mielellämme. Ota yhteyttä osoitteeseen servicedesk@csc.fi

Ystävällisin terveisin,

IDA-tiimi
"

#--------------------------------------------------------------------------------

OUTPUT="/var/tmp/$$.output"
SUMMARY="/var/tmp/$$.summary"

source $ROOT/venv/bin/activate

python -u $ROOT/utils/admin/lib/audit_old_data.py $ROOT $PROJECT $MAX_AGE $QUIET > $OUTPUT

if [ $? -ne 0 ]; then
    errorExit "Auditing of old data for project $PROJECT failed"
fi

jq --arg REPORT "$REPORT" '.reportPathname = $REPORT' --indent 4 < $OUTPUT > $REPORT

if [ $? -ne 0 ]; then
    errorExit "Formatting of old data report for project $PROJECT failed"
fi

TOTAL_BYTES=`cat "$REPORT"         | jq -r '.totalBytes'`
TOTAL_FILES=`cat "$REPORT"         | jq -r '.totalFiles'`
TOTAL_FROZEN_BYTES=`cat "$REPORT"  | jq -r '.totalFrozenBytes'`
TOTAL_FROZEN_FILES=`cat "$REPORT"  | jq -r '.totalFrozenFiles'`
TOTAL_STAGING_BYTES=`cat "$REPORT" | jq -r '.totalStagingBytes'`
TOTAL_STAGING_FILES=`cat "$REPORT" | jq -r '.totalStagingFiles'`

TOTAL_BYTES_HR=$(bytesToHR "$TOTAL_BYTES")
TOTAL_FROZEN_BYTES_HR=$(bytesToHR "$TOTAL_FROZEN_BYTES")
TOTAL_STAGING_BYTES_HR=$(bytesToHR "$TOTAL_STAGING_BYTES")

printf "\n" > $SUMMARY
printf "%-25s%s\n" "Project:"              "${PROJECT}"                >> $SUMMARY
printf "%-25s%s\n" "Total bytes:"          "${TOTAL_BYTES_HR}"         >> $SUMMARY
printf "%-25s%s\n" "Total files:"          "${TOTAL_FILES}"            >> $SUMMARY
printf "%-25s%s\n" "Total frozen bytes:"   "${TOTAL_FROZEN_BYTES_HR}"  >> $SUMMARY
printf "%-25s%s\n" "Total frozen files:"   "${TOTAL_FROZEN_FILES}"     >> $SUMMARY
printf "%-25s%s\n" "Total staging bytes:"  "${TOTAL_STAGING_BYTES_HR}" >> $SUMMARY
printf "%-25s%s\n" "Total staging files:"  "${TOTAL_STAGING_FILES}"    >> $SUMMARY
printf "\n\n" >> $SUMMARY

# If there is old data, send email to project users, unless explicitly excluded

if [ -z "$NO_USER_EMAIL" ]; then

    if [ $TOTAL_BYTES -gt 0 ]; then

        # Normally, we don't send project-specific notices to internal recipients, only in dev environment
        if [ "$IDA_ENVIRONMENT" != "DEV" ]; then
            EMAIL_RECIPIENTS="" # clear any internal recipients defined in service configuration
        fi

        export ROOT
        export EMAIL_SENDER
        export EMAIL_RECIPIENTS
    
        SUBJECT="Notice: Project $PROJECT has files in IDA which haven't been included in any dataset"
    
        OUTPUT=`$ROOT/utils/admin/email-project-users "$PROJECT" "$SUBJECT" "$MESSAGE"`

        if [ "$QUIET" != "true" ]; then
            echo "$OUTPUT" >&2
        fi
    else
        if [ "$QUIET" != "true" ]; then
            echo "No emails sent to project users (no old data)" >&2
        fi
    fi
else
    if [ "$QUIET" != "true" ]; then
        echo "No emails sent to project users (excluded)" >&2
    fi
fi

# Output results
    
if [ "$JSON_OUTPUT" ]; then
    cat $REPORT | jq 'del(.frozenFiles) | del(.stagingFiles)' --indent 4
else
    if [ $TOTAL_BYTES -gt 0 ]; then
        cat $SUMMARY
    else
        if [ "$QUIET" != "true" ]; then
            echo "No old data found in project $PROJECT" >&2
        fi
    fi
fi

#--

rm -f $OUTPUT 2>/dev/null
rm -f $SUMMARY 2>/dev/null

addToLog "DONE"
