#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# This script will query the CSC Data Deletion Process microservice to obtain a
# list of all projects which are closed and have either a grace or deletedata
# substate, and then will suspend each project which is not yet suspended and
# will delete each project which has a deletedata substate.
#
# It is expected that this script will be executed nightly.
# --------------------------------------------------------------------------------

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT"
PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

echo "Retrieving list of projects with a CSC data deletion process substate 'grace'..."

GRACE_PROJECTS=`$ROOT/utils/admin/list-grace-projects 2>$ERR`

if [ -s $ERR ]; then
    cat $ERR >&2
    errorExit "Failed to retrieve grace projects"
fi

echo "Retrieving list of projects with a CSC data deletion process substate 'deletedata'..."

DELETEDATA_PROJECTS=`$ROOT/utils/admin/list-deletedata-projects 2>$ERR`

if [ -s $ERR ]; then
    cat $ERR >&2
    errorExit "Failed to retrieve deletedata projects"
fi

echo "Retrieving list of projects which are already suspended..."

SUSPENDED_PROJECTS=`$ROOT/utils/admin/list-suspended-projects 2>$ERR`

if [ -s $ERR ]; then
    cat $ERR >&2
    errorExit "Failed to retrieve suspended projects"
fi

for PROJECT in $GRACE_PROJECTS; do

    IS_SUSPENDED=`echo "$SUSPENDED_PROJECTS" | grep "$PROJECT"`

    if [ "$IS_SUSPENDED" = "" ]; then

        # Only actually suspend the project if in production, otherwise just inform about appropriate actions but do nothing

        if [ "$IDA_ENVIRONMENT" = "PRODUCTION" ]; then

            $ROOT/utils/admin/suspend-project $PROJECT --delete 2>$ERR

            if [ -s $ERR ]; then
                cat $ERR >&2
                errorExit "Failed to suspend project ${PROJECT}"
            fi

            echoAndLog "Project ${PROJECT} has been suspended"
    
        else

            echo "Project ${PROJECT} should be suspended"

        fi

    else

        echo "Project ${PROJECT} is already suspended"

    fi

done

for PROJECT in $DELETEDATA_PROJECTS; do

    # Only actually delete the project if in production, otherwise just inform about appropriate actions but do nothing

    if [ "$IDA_ENVIRONMENT" = "PRODUCTION" ]; then

        $ROOT/utils/admin/delete-project $PROJECT 2>$ERR

        if [ -s $ERR ]; then
            cat $ERR >&2
            errorExit "Failed to delete project ${PROJECT}"
        fi

        echoAndLog "Project ${PROJECT} has been deleted"
    
    else

        echo "Project ${PROJECT} should be deleted"

    fi

done

#--------------------------------------------------------------------------------

rm $ERR 2>/dev/null

addToLog "DONE"
