#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2024 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`
PROJECT="null"

USAGE="
Usage: $SCRIPT [days]
       $SCRIPT -h
"

#--------------------------------------------------------------------------------

# Check if the days parameter was passed and that it is a positive number

DAYS=${1//[^0-9]/}

if [ -z "$DAYS" ]; then
    echo "$USAGE" >&2
    exit 1
fi

#--------------------------------------------------------------------------------

# Initialize script with common definitions

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

echoAndLog "Deleting project trash folders older than ${DAYS} days old"

if [ "$DAYS" = "0" ]; then
    EXPIRED_FOLDERS=$(find "$TRASH_DATA_ROOT" -maxdepth 1 -mindepth 1 -type d -print)
else
    EXPIRED_FOLDERS=$(find "$TRASH_DATA_ROOT" -maxdepth 1 -mindepth 1 -type d -daystart -mtime +$DAYS -print)
fi

if [ -n "$EXPIRED_FOLDERS" ]; then
    for EXPIRED_FOLDER in $EXPIRED_FOLDERS; do
        echoAndLog "Deleting project trash folder: ${EXPIRED_FOLDER}"
        rm -fr "$EXPIRED_FOLDER" 2>$ERR
        if [ -s $ERR ]; then
            cat $ERR >&2
            errorExit "Failed to delete project trash folder: ${EXPIRED_FOLDER}"
        fi
    done
else
    echoAndLog "No project trash folders to be deleted"
fi

#--------------------------------------------------------------------------------

rm $ERR 2>/dev/null

addToLog "DONE"
