#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#---------------------------------------------------------------------------------
# NOTE: Unlike most admin scripts, this particular script does not load any
# common configuration or initialization script but is fully stand-alone.
#--------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT project subject message
       $SCRIPT -h
"

#--------------------------------------------------------------------------------

ERR="/var/tmp/ida_${SCRIPT}_$$.err"

cleanup() {
    rm -f $ERR 2>/dev/null
}

trap cleanup EXIT

#--------------------------------------------------------------------------------

# If there is no email sender configured in the environment, we do nothing

if [ "$EMAIL_SENDER" = "" ]; then
    echo "Warning: No email sender configured. Exiting." >&2
    exit
fi

#--------------------------------------------------------------------------------

PROJECT="$1"

if [ "$PROJECT" = "" ]; then
    echo "No project specified" >&2
    exit 1
fi

SUBJECT="$2"

if [ "$SUBJECT" = "" ]; then
    echo "No email subject specified" >&2
    exit 1
fi

MESSAGE="$3"

if [ "$MESSAGE" = "" ]; then
    echo "No email message specified" >&2
    exit 1
fi

#--------------------------------------------------------------------------------

SUBJECT=`echo "$2" | tr '\n' ' '`
SUBJECT="[IDA Service] ${SUBJECT}"

MESSAGE="${MESSAGE}

[This is an automated IDA service message regarding project ${PROJECT} sent to all project users]
"

#--------------------------------------------------------------------------------

RECIPIENTS=`$ROOT/utils/admin/fetch-project-emails "$PROJECT" 2>/dev/null`

if [ "$DEBUG" = "true" ]; then
    echo "From:    ${EMAIL_SENDER}"     >&2
    echo "To:      ${RECIPIENTS}"       >&2
    echo "BCC:     ${EMAIL_RECIPIENTS}" >&2
    echo "Project: ${PROJECT}"          >&2
    echo "Subject: ${SUBJECT}"          >&2
    echo "Message: ${MESSAGE}"          >&2
fi

# If neither project nor internal recipients are defined, we do nothing

if [ "${RECIPIENTS}${EMAIL_RECIPIENTS}" = "" ]; then
    echo "No project nor internal recipients. Exiting." >&2
    exit
fi

if [ "$RECIPIENTS" = "" ]; then
    echo "Warning: The project ${PROJECT} has no users!" >&2
fi

# If internal recipients are defined in configuration, add internal recipients 

if [ "$EMAIL_RECIPIENTS" != "" ]; then
    if [ "$RECIPIENTS" = "" ]; then
        RECIPIENTS="$EMAIL_RECIPIENTS"
    else
        RECIPIENTS="-b $EMAIL_RECIPIENTS $RECIPIENTS"
    fi
fi

SNAIL=`mail --version 2>/dev/null | grep -- 's-nail'`

if [ -z "$SNAIL" ]; then
    echo "$MESSAGE" | mail -s "$SUBJECT" -r $EMAIL_SENDER -S "replyto=$EMAIL_SENDER" $RECIPIENTS 2>$ERR
else
    echo "$MESSAGE" | mail -s "$SUBJECT" -r $EMAIL_SENDER -S "reply-to=$EMAIL_SENDER" $RECIPIENTS 2>$ERR
fi

if [ -s $ERR ]; then
    cat $ERR >&2
    echo "Failed to send email to project users!" >&2
    exit 1
fi

echo "Email sent to all project ${PROJECT} users and/or default internal recipients."
