#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT project subject message"

INIT_FILE=`dirname $0`/lib/init_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

SUBJECT="$2"

if [ "$SUBJECT" = "" ]; then
    errorExit "No email subject specified"
fi

MESSAGE="$3"

if [ "$MESSAGE" = "" ]; then
    errorExit "No email message specified"
fi

#--------------------------------------------------------------------------------

if [ "$EMAIL_SENDER" != "" ]; then

    RECIPIENTS=`$ROOT/utils/admin/fetch-project-emails $PROJECT`

    if [ "$RECIPIENTS" = "" ]; then
        echo "Warning: The project ${PROJECT} has no users!"
    fi

    MESSAGE="${MESSAGE}

If you have any questions, please contact the CSC Service Desk (servicedesk@csc.fi).

[This is an automated IDA service message regarding project ${PROJECT} sent to all project users]
"

echo "From:    ${EMAIL_SENDER}"
echo "To:      ${RECIPIENTS}"
echo "BCC:     ${EMAIL_RECIPIENTS}"
echo "Project: ${PROJECT}"
echo "Subject: ${SUBJECT}"
echo "Message: ${MESSAGE}"

    sendEmail "${SUBJECT}" "${MESSAGE}" "${RECIPIENTS}" 2>$ERR

    if [ -s $ERR ]; then
        cat $ERR | tee -a $LOG
        errorExit "Error: Failed to send email to project users!"
    fi

    echo "Email sent to all project ${PROJECT} users and default internal recipients."

fi
