#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2020 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT"
PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_audit_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

FIRST="true"

echo "{"

for PROJECT in `$ROOT/utils/admin/list-projects`; do

    if [ "$FIRST" != "true" ]; then
        echo ","
    fi

    FIRST="false"

    TOTAL_FILES=0
    FROZEN_FILES=0

    echo "    \"${PROJECT}\": {"

    DATA=`$ROOT/utils/admin/fetch-project-file-counts $PROJECT 2>/dev/null`

    if [ "$DATA" != "" ]; then
        TOTAL_FILES=`echo "$DATA" | grep "totalFiles" | sed -e 's/^[^0-9]*//' | sed -e 's/[^0-9]*$//'`
        FROZEN_FILES=`echo "$DATA" | grep "frozenFiles" | sed -e 's/^[^0-9]*//' | sed -e 's/[^0-9]*$//'`
    fi

    echo "        \"totalFiles\":  ${TOTAL_FILES},"
    echo "        \"frozenFiles\": ${FROZEN_FILES}"

    echo -n "    }"

done

echo ""
echo "}"

addToLog "DONE"
