#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2022 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT id"
PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

if [ "$CSC_DATA_DELETION_MICROSERVICE" == "" ]; then
    echo "The variable CSC_DATA_DELETION_MICROSERVICE is not defined in the configuration. Aborting." >&2
    exit 1
fi

WORKFLOW_ID="$1"

if [ -z "$WORKFLOW_ID" ]
then
    echo "$USAGE"
    exit 1
fi

#--------------------------------------------------------------------------------

OUT=`curl --fail -k -s -S "$CSC_DATA_DELETION_MICROSERVICE/workflow?id=$WORKFLOW_ID" 2>$ERR`

if [ -s $ERR ]; then
    MSG=`cat $ERR`
    addToLog "$MSG"
    echo "$MSG"
    errorExit "Failed to retrieve workflow details"
fi

MSG=`echo $OUT | tr "\n" " " `
addToLog "$MSG"
echo "$OUT"

addToLog "DONE"
