#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2020 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT [csv]"
PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_audit_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

FIRST="true"

if [ "$1" = "csv" ]; then

    for PROJECT in `$ROOT/utils/admin/list-projects`; do
        if [ "$FIRST" == "true" ]; then
            $ROOT/utils/admin/fetch-project-stats $PROJECT csv 2>/dev/null
            FIRST="false"
        else
            $ROOT/utils/admin/fetch-project-stats $PROJECT csv 2>/dev/null | tail -1
        fi
    done

    addToLog "DONE"
    exit 0
fi

#--------------------------------------------------------------------------------

echo "{"

for PROJECT in `$ROOT/utils/admin/list-projects`; do

    if [ "$FIRST" != "true" ]; then
        echo ","
    fi

    FIRST="false"

    echo "    \"${PROJECT}\": {"

    $ROOT/utils/admin/fetch-project-stats $PROJECT 2>/dev/null \
        | grep -v '"project": ' \
        | grep -v '[\{\}]' \
        | sed -e 's/^/    /'

    echo -n "    }"

done

echo ""
echo "}"

addToLog "DONE"
