#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# This script returns data change details for a specified project, from most
# recent to least recent

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT project [limit]
       $SCRIPT -h

       project = the project name
       limit   = the number of change events to return (default = 1)
"

#--------------------------------------------------------------------------------
# Initialize script with common definitions

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------
# Process command line arguments

if [ "$#" -gt 2 ]; then
    echo "$USAGE" >&2
    errorExit "Invalid number of arguments"
fi

PROJECT="$1"
LIMIT=`echo "$2" | sed -e 's/[^0-9]//g'`

if [ "$LIMIT" = "" ]; then
    LIMIT="1"
fi

#--------------------------------------------------------------------------------

URL="$IDA_API/dataChanges/${PROJECT}?limit=$LIMIT"

if [ "$DEBUG" = "true" ]
then
    echo "PROJECT: $PROJECT"
    echo "ACTION:  $ACTION"
    echo "REQUEST: $CURL_GET $PROJECT_USER_CREDENTIALS -H \"$IDA_MODE_HEADER\" \"${URL}\""
fi

if [ ! -d $PROJECT_STORAGE_OC_DATA_ROOT ]; then
    errorExit "The specified project ${PROJECT} does not exist"
fi

OUT=`$CURL_GET $PROJECT_USER_CREDENTIALS -H "$IDA_MODE_HEADER" "${URL}" 2>$ERR `

if [ -s $ERR ]; then
    MSG=`cat $ERR`
    addToLog "$MSG"
    errorExit "Failed to retrieve change details"
fi

echo "$OUT" | jq --indent 4

addToLog "DONE"
