#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2020 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

# This script scans key database tables to determine which projects have had
# any activity since the specified date(time), if given, or during the past
# 24 hours if no date(time) is specified. If only a date is specified, the time
# T00:00:00Z is used.

# --------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT [ts]
       $SCRIPT -h

       ts   an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/ (defaults to 24 hours ago)
"

PROJECT="null"
SINCE="$1"

# --------------------------------------------------------------------------------
# Initialize script with common definitions

INIT_FILE=`dirname "$(realpath $0)"`/lib/init_audit_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------
# If date(time) not specified, calculate datetime for 24 hours ago. If only date
# specified, add default time component for beginning of that day.

if [ "$SINCE" != "" ]; then
    if [[ ! "$SINCE" =~ ^[12][0-9]{3}-[01][0-9]-[0-3][0-9]T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
        if [[ "$SINCE" =~ ^[12][0-9]{3}-[01][0-9]-[0-3][0-9]$ ]]; then
            SINCE="${SINCE}T00:00:00Z"
        else
            errorExit "Invalid timestamp: $SINCE"
        fi
    fi
fi

if [ "$SINCE" = "" ]; then
    SINCE=`TZ=UTC date -d "$SINCE - 24 hours" +"%Y-%m-%dT%H:%M:%SZ"`
fi

if [ "$DEBUG" = "true" ]; then
    echo "SINCE:         $SINCE" >&2
fi

if [[ "$SINCE" > "$START" ]]; then
    errorExit "Specified timestamp $SINCE is in the future"
fi

source $ROOT/venv/bin/activate

python -u $ROOT/utils/admin/lib/list-active-projects.py $ROOT $SINCE $START

if [ $? -ne 0 ]; then
    errorExit "Failed to retrieve listing of active projects"
fi

addToLog "DONE"
