#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT
       $SCRIPT -h
"

PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

ldapsearch -x -H "$LDAP_HOST_URL" -D "$LDAP_BIND_USER" -w "$LDAP_PASSWORD" -b "$LDAP_SEARCH_BASE" \
    '(&(objectClass=CSCServiceIDAClass)(CSCServiceIDAQuotaGranter=cn=00006,ou=Organizations,o=CSC))' CSCPrjNUM \
    | grep 'CSCPrjNUM: ' | sed -e 's/^.*CSCPrjNUM: *//' -e 's/  *$//' | sort | uniq

addToLog "DONE"
