#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT project"

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

if [ ! -d "${STORAGE_OC_DATA_ROOT}/${PROJECT_USER_PREFIX}${PROJECT}/files" ]; then
    errorExit "The project '${PROJECT}' does not exist"
fi

DATA=`$ROOT/utils/admin/fetch-project-stats $PROJECT`

QUOTA=`echo "$DATA" | jq -r '.quotaBytes'`
QUOTA=`bytesToHR "0${QUOTA}"`

USED=`echo "$DATA" | jq -r '.totalBytes'`
USED=`bytesToHR "0${USED}"`

STAGED_VOLUME=`echo "$DATA" | jq -r '.stagedBytes'`
STAGED_VOLUME=`bytesToHR "0${STAGED_VOLUME}"`

FROZEN_VOLUME=`echo "$DATA" | jq -r '.frozenBytes'`
FROZEN_VOLUME=`bytesToHR "0${FROZEN_VOLUME}"`

TOTAL_FILES=`echo "$DATA" | jq -r '.totalFiles'`
STAGED_FILES=`echo "$DATA" | jq -r '.stagedFiles'`
FROZEN_FILES=`echo "$DATA" | jq -r '.frozenFiles'`

LAST_DATA_CHANGE=`echo "$DATA" | jq -r '.lastDataChange' | sed -e 's/T.*$//'`

STORAGE_VOLUME=`echo "$DATA" | jq -r '.storageVolume'`

echo "Quota:"
echo "    ${QUOTA}"

echo "Used:"
echo "    ${USED}"

echo "Staged:"
echo "    ${STAGED_VOLUME}"

echo "Frozen:"
echo "    ${FROZEN_VOLUME}"

echo "Total files:"
echo "    ${TOTAL_FILES}"

echo "Staged files:"
echo "    ${STAGED_FILES}"

echo "Frozen files:"
echo "    ${FROZEN_FILES}"

echo "Last data change:"
echo "    ${LAST_DATA_CHANGE}"

echo "Storage volume:"
echo "    ${STORAGE_VOLUME}"

echo "Users: "

$CURL_GET $ADMIN_CREDENTIALS -H "$IDA_MODE_HEADER" -H "OCS-APIRequest: true" "${LOCAL_ROOT_URL}/ocs/v1.php/cloud/groups/${PROJECT}" | \
    grep "<element>" | grep -v "<element>${PROJECT_USER_PREFIX}" | sed -e 's/^.*<element>/    /' | sed -e 's/<.*$//' 

echo "Action status: "

$CURL_GET $PROJECT_USER_CREDENTIALS -H "$IDA_MODE_HEADER" "$IDA_API_ROOT_URL/status" | jq --indent 4 | \
    grep -e '"failed"' -e '"pending"' -e '"suspended"' | sed -e 's/, *$//' -e 's/"//g' | sort -r 

addToLog "DONE"
