#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

SCRIPT_PATHNAME=`basename "$(realpath $0)"`
SCRIPT=`basename "$SCRIPT_PATHNAME"`

USAGE="Usage: $SCRIPT [ credentials_file ]
       $SCRIPT -h"

. `dirname $0`/../../lib/init_script.sh

if [ "$ROOT" = "" ]; then
    echo "Error: The ROOT environment variable is not defined. Aborting." >&2
    exit 1
fi

export ROOT

#--------------------------------------------------------------------------------
# Verify that we are not in production

if [ "$IDA_ENVIRONMENT" = "PRODUCTION" ]; then
    echo "Error: This script can not be run in a production environment. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

if [ "$1" = "-h" ]; then
    echo "$USAGE"
    exit
fi

if [ "$1" = "" ]; then
    echo "Error: missing credentials file argument" >&2
    exit 1
fi

if [ ! -d $ROOT/venv ]; then
    echo "Error: python virtual environment ${ROOT}/venv not found" >&2
    exit 1
fi

source $ROOT/venv/bin/activate

python $ROOT/utils/admin/lib/push-credentials-to-test-idm.py $*
