#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT project [--delete | --silent]
       $SCRIPT -h

       project  = the project name
       --delete = the project users will be sent a more detailed message regarding deletion of the project
       --silent = no email will be sent to project users
"

#--------------------------------------------------------------------------------
# Initialize script with common definitions

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------
echo "Verifying project ${PROJECT} exists..."

if [ ! -d $PROJECT_STORAGE_OC_DATA_ROOT ]; then
    errorExit "The specified project ${PROJECT} does not exist"
fi

#--------------------------------------------------------------------------------
echo "Checking if project ${PROJECT} is already suspended..."

PIDS=`$CURL_GET $ADMIN_CREDENTIALS -H "$IDA_MODE_HEADER" "$IDA_API_ROOT_URL/actions?status=suspend" 2>$ERR | \
      tr "\n" " " | tr "{" "\n" | grep "\"action\": *\"suspend\"" | grep "\"project\": *\"$PROJECT\"" | \
      sed -e 's/^.*"pid": *"//' | sed -e 's/".*$//'`

if [ -s $ERR ]; then
    MSG=`cat $ERR`
    addToLog "$MSG"
    errorExit "Failed to retrieve pending actions for project"
fi

if [ "$PIDS" != "" ]; then
    echoAndLog "The specified project ${PROJECT} is already suspended"
    addToLog "DONE"
    exit 0
fi

#--------------------------------------------------------------------------------
echo "Locking project ${PROJECT}..."

if [ "$DEBUG" = "true" ]; then
    echo "$CURL_POST \"$PROJECT_USER_CREDENTIALS\" -H \"$IDA_MODE_HEADER\" \"$IDA_API_ROOT_URL/lock/${PROJECT}\""
fi

OUT=`$CURL_POST $PROJECT_USER_CREDENTIALS -H "$IDA_MODE_HEADER" "$IDA_API_ROOT_URL/lock/${PROJECT}" 2>&1`

if [ ! -e $PROJECT_LOCK ]; then
    errorExit "Failed to lock project ${PROJECT}"
fi

#--------------------------------------------------------------------------------
echo "Creating suspend action for project ${PROJECT}..."

if [ "$DEBUG" = "true" ]; then
     echo "$CURL_POST $ADMIN_CREDENTIALS -H \"$IDA_MODE_HEADER\" \"$IDA_API_ROOT_URL/actions?project=$PROJECT&action=suspend&pathname=/\""
fi

OUT=`$CURL_POST $ADMIN_CREDENTIALS -H "$IDA_MODE_HEADER" "$IDA_API_ROOT_URL/actions?project=$PROJECT&action=suspend&pathname=/"`

SUCCESS=`echo "$OUT" | grep '"pid":'`

if [ "$SUCCESS" = "" ]; then
    errorExit "Failed to create suspend action for project ${PROJECT}"
fi

rm $ERR 2>/dev/null

#--------------------------------------------------------------------------------
# The SUSPEND sentinel file in the project /files/ directory is redundant with
# the suspend action which is the primary means of tracking whether a project
# is suspended, and when it was suspended (and possibly unsuspended). The 
# sentinel file provides a quick and easy way for scripts and other components
# to test if a project is suspended without having to query the database.

echo "Creating suspend sentinel file for project ${PROJECT}..."

touch $PROJECT_SUSPENDED

if [ ! -e $PROJECT_SUSPENDED ]; then
    errorExit "Failed to create suspend sentinel file for project ${PROJECT}"
fi

#--------------------------------------------------------------------------------

echoAndLog "Project ${PROJECT} suspended."

#--------------------------------------------------------------------------------

if [ "$2" = "--silent" ]; then
    addToLog "DONE"
    exit
fi

if [ "$2" = "--delete" ]; then
    SUBJECT="Project ${PROJECT} will be removed from the IDA service."
    MESSAGE="You are a member of the CSC project ${PROJECT}, which has had rights to use the IDA service.

The project will be REMOVED from the IDA service in accordance with the official CSC Data Deletion Policy (https://docs.csc.fi/accounts/how-to-manage-your-project/#project-closure).

The project is now SUSPENDED in the IDA service.

The removal is either due to having no active users in the service, or due to an agreement with the project manager and/or organization's IDA contact person.

If the project has any data in IDA, that data will be deleted during the final removal step as agreed with the project manager and/or organization's IDA contact person.

You will receive a notification when the project has been removed from the service."
else
    SUBJECT="Project ${PROJECT} suspended."
    MESSAGE="The project ${PROJECT} has been SUSPENDED in the IDA service. Access to the project space is now READ-ONLY."
fi

$ROOT/utils/admin/email-project-users "$PROJECT" "$SUBJECT" "$MESSAGE"

addToLog "DONE"
