version: '3.8'

services:
  ida-nextcloud:
    image: fairdata-ida-nextcloud
    volumes:
      # Map each wanted subdirectory separately since Nextcloud user needs write permission to the nextcloud
      # subdirectory within the container - feel free to come up with a prettier solution...
      - ./utils:/var/ida/utils
#     - ./nextcloud/3rdparty:/var/ida/nextcloud/3rdparty
#     - ./nextcloud/core:/var/ida/nextcloud/core
#     - ./nextcloud/lib:/var/ida/nextcloud/lib
#     - ./nextcloud/ocs:/var/ida/nextcloud/ocs
#     - ./nextcloud/ocs-provider:/var/ida/nextcloud/ocs-provider
#     - ./nextcloud/resources:/var/ida/nextcloud/resources
#     - ./nextcloud/settings:/var/ida/nextcloud/settings
      - ./nextcloud/themes:/var/ida/nextcloud/themes
#     - ./nextcloud/updater:/var/ida/nextcloud/updater
#     - ./nextcloud/.user.ini:/var/ida/nextcloud/.user.ini
#     - ./nextcloud/console.php:/var/ida/nextcloud/console.php
#     - ./nextcloud/cron.php:/var/ida/nextcloud/cron.php
#     - ./nextcloud/index.html:/var/ida/nextcloud/index.html
#     - ./nextcloud/index.php:/var/ida/nextcloud/index.php
#     - ./nextcloud/public.php:/var/ida/nextcloud/public.php
#     - ./nextcloud/remote.php:/var/ida/nextcloud/remote.php
#     - ./nextcloud/robots.txt:/var/ida/nextcloud/robots.txt
#     - ./nextcloud/status.php:/var/ida/nextcloud/status.php
#     - ./nextcloud/version.php:/var/ida/nextcloud/version.php

#     # ...likewise write permission is needed for nextcloud/apps directory
#     - ./nextcloud/apps/admin_audit:/var/ida/nextcloud/apps/admin_audit
#     - ./nextcloud/apps/cloud_federation_api:/var/ida/nextcloud/apps/cloud_federation_api
#     - ./nextcloud/apps/dav:/var/ida/nextcloud/apps/dav
#     - ./nextcloud/apps/federatedfilesharing:/var/ida/nextcloud/apps/federatedfilesharing
#     - ./nextcloud/apps/files:/var/ida/nextcloud/apps/files
#     - ./nextcloud/apps/files_sharing:/var/ida/nextcloud/apps/files_sharing
      - ./nextcloud/apps/ida:/var/ida/nextcloud/apps/ida
#     - ./nextcloud/apps/idafirstrunwizard:/var/ida/nextcloud/apps/idafirstrunwizard
#     - ./nextcloud/apps/lookup_server_connector:/var/ida/nextcloud/apps/lookup_server_connector
#     - ./nextcloud/apps/oauth2:/var/ida/nextcloud/apps/oauth2
#     - ./nextcloud/apps/provisioning_api:/var/ida/nextcloud/apps/provisioning_api
#     - ./nextcloud/apps/twofactor_backupcodes:/var/ida/nextcloud/apps/twofactor_backupcodes
#     - ./nextcloud/apps/user_saml:/var/ida/nextcloud/apps/user_saml
#     - ./nextcloud/apps/workflowengine:/var/ida/nextcloud/apps/workflowengine
      - type: volume
        source: ida-storage-vol
        target: /mnt/storage_vol01/ida
      - type: volume
        source: ida-replication-storage-vol
        target: /mnt/storage_vol01/ida_replication
    configs:
      - source: ida-httpd-config
        target: '/etc/apache2/sites-enabled/ida.conf'
      - source: fairdata-ssl-certificate
        target: '/etc/pki/tls/certs/ssl.crt.pem'
      - source: fairdata-ssl-certificate-key
        target: '/etc/pki/tls/private/ssl.key.pem'
      - source: fairdata-test-accounts-projects
        target: '/var/fairdata-test-accounts/config/projects.json'
      - source: fairdata-test-accounts-users
        target: '/var/fairdata-test-accounts/config/users.json'
      - source: fairdata-test-accounts-credentials
        target: '/var/fairdata-test-accounts/config/credentials.json'
      - source: fairdata-test-accounts-initialize
        target: '/var/fairdata-test-accounts/initialize-ida-accounts'
    networks:
      default:
        aliases:
          - ida.fd-dev.csc.fi
    ports:
      - 443:443

  ida-metadata:
    image: fairdata-ida-metadata
    volumes:
      - ./agents:/var/ida/agents
      - type: volume
        source: ida-storage-vol
        target: /mnt/storage_vol01/ida
      - type: volume
        source: ida-replication-storage-vol
        target: /mnt/storage_vol01/ida_replication
    configs:
      - source: ida-sh-config
        target: '/var/ida/config/config.sh'

  ida-replication:
    image: fairdata-ida-replication
    volumes:
      - ./agents:/var/ida/agents
      - type: volume
        source: ida-storage-vol
        target: /mnt/storage_vol01/ida
      - type: volume
        source: ida-replication-storage-vol
        target: /mnt/storage_vol01/ida_replication
    configs:
      - source: ida-sh-config
        target: '/var/ida/config/config.sh'

  ida-db:
    image: postgres:12
    hostname: ida-db
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: foo

  ida-redis:
    image: redis
    hostname: ida-redis

  ida-rabbitmq:
    image: rabbitmq:management
    hostname: ida-rabbitmq
    ports:
      - 15672:15672
    configs:
      - source: ida-rabbitmq-config
        target: '/etc/rabbitmq/rabbitmq.conf'

  fairdata-nginx:
    image: nginx
    configs:
      - source: fairdata-nginx-config
        target: '/etc/nginx/nginx.conf'
      - source: fairdata-ssl-certificate
        target: '/etc/pki/tls/certs/ssl.crt.pem'
      - source: fairdata-ssl-certificate-key
        target: '/etc/pki/tls/private/ssl.key.pem'
      - source: ida-nginx-config
        target: '/etc/nginx/sites-enabled/ida'
#    ports:
#      - 443:443

configs:
  ida-php-config:
    external: True
  ida-sh-config:
    external: True
  ida-httpd-config:
    external: True
  ida-nginx-config:
    external: True
  ida-rabbitmq-config:
    external: True

  fairdata-nginx-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True

  fairdata-test-accounts-projects:
    external: True
  fairdata-test-accounts-users:
    external: True
  fairdata-test-accounts-credentials:
    external: True
  fairdata-test-accounts-initialize:
    external: True

volumes:
  ida-storage-vol:
    external: True
  ida-replication-storage-vol:
    external: True
