version: '3.8'

services:

  ida-nextcloud:
    image: fairdata-ida-nextcloud
    hostname: ida.fd-dev.csc.fi
    volumes:
      - .:/var/ida
      - ../ida2-command-line-tools:/var/ida-tools
      - ../ida-service-internals/report:/opt/fairdata/ida-report
      - ../fairdata-ida-admin-portal:/opt/fairdata/ida-admin-portal
      - ../fairdata-test-accounts:/opt/fairdata/fairdata-test-accounts
      - ../fairdata-ida-healthcheck:/usr/local/fd/fairdata-ida-healthcheck
      - ../fairdata-download:/usr/local/fd/fairdata-download
    configs:
      - source: ida-httpd-config
        target: '/etc/httpd/conf/httpd.conf'
      - source: ida-httpd-ssl-config
        target: '/etc/httpd/conf.d/ssl.conf'
      - source: ida-httpd-modsecurity-config
        target: '/etc/httpd/conf.d/mod_security.conf'
      - source: ida-httpd-modsecurity-crs-config
        target: '/etc/httpd/modsecurity.d/crs-setup.conf'
      - source: ida-httpd-modsecurity-nextcloud-config
        target: '/etc/httpd/modsecurity.d/activated_rules/REQUEST-903.9003-NEXTCLOUD-EXCLUSION-RULES.conf'
      - source: fairdata-ssl-certificate
        target: '/etc/pki/tls/certs/ssl.crt.pem'
      - source: fairdata-ssl-certificate-key
        target: '/etc/pki/tls/private/ssl.key.pem'
    networks:
      default:
        aliases:
          - ida.fd-dev.csc.fi
    ports:
      - 80:80
      - 443:443
      - 4431:4431
      - 5000:5000
      - 8888:8888

  ida-db:
    image: postgres:12
    hostname: ida-db
    environment:
      POSTGRES_USER: nextcloud      # = /var/ida/config.sh:$DBUSER
      POSTGRES_PASSWORD: nextcloud  # = /var/ida/config.sh:$DBPASSWORD
      POSTGRES_DB: nextcloud        # = /var/ida/config.sh:$DBNAME

  ida-redis:
    image: redis
    hostname: ida-redis

  ida-rabbitmq:
    image: rabbitmq:management
    hostname: ida-rabbitmq
    ports:
      - 15672:15672
    configs:
      - source: ida-rabbitmq-config
        target: '/etc/rabbitmq/rabbitmq.conf'

configs:
  ida-php-config:
    external: True
  ida-sh-config:
    external: True
  ida-httpd-config:
    external: True
  ida-httpd-ssl-config:
    external: True
  ida-httpd-modsecurity-config:
    external: True
  ida-httpd-modsecurity-crs-config:
    external: True
  ida-httpd-modsecurity-nextcloud-config:
    external: True
  ida-rabbitmq-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True