FROM python:3.8-buster

WORKDIR /var/ida

# Install application requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copy repository contents
COPY agents agents
COPY lib lib

# Initialize directories
RUN mkdir -p /mnt/storage_vol01/ida \
 && mkdir -p /mnt/storage_vol01/log \
 && chown 33:33 /mnt/storage_vol01/ida \
 && chown 33:33 /mnt/storage_vol01/log

USER 33:33

CMD ["python", "-m", "agents.replication.replication_agent"]
