version: '3.8'

services:
  ida-nextcloud:
    image: fairdata-ida-nextcloud
    volumes:
      - .:/var/ida
    configs:
      - source: ida-httpd-config
        target: '/etc/apache2/sites-enabled/ida.conf'
      - source: fairdata-ssl-certificate
        target: '/etc/pki/tls/certs/ssl.crt.pem'
      - source: fairdata-ssl-certificate-key
        target: '/etc/pki/tls/private/ssl.key.pem'
      - source: fairdata-test-accounts-projects
        target: '/var/fairdata-test-accounts/config/projects.json'
      - source: fairdata-test-accounts-users
        target: '/var/fairdata-test-accounts/config/users.json'
      - source: fairdata-test-accounts-credentials
        target: '/var/fairdata-test-accounts/config/credentials.json'
      - source: fairdata-test-accounts-initialize
        target: '/var/fairdata-test-accounts/initialize-ida-accounts'
    networks:
      default:
        aliases:
          - ida.fd-dev.csc.fi
    ports:
      - 443:443

  ida-db:
    image: postgres:12
    hostname: ida-db
    environment:
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: nextcloud
      POSTGRES_DB: postgres

  ida-redis:
    image: redis
    hostname: ida-redis

  ida-rabbitmq:
    image: rabbitmq:management
    hostname: ida-rabbitmq
    ports:
      - 15672:15672
    configs:
      - source: ida-rabbitmq-config
        target: '/etc/rabbitmq/rabbitmq.conf'

configs:
  ida-php-config:
    external: True
  ida-sh-config:
    external: True
  ida-httpd-config:
    external: True
  ida-rabbitmq-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True
  fairdata-test-accounts-projects:
    external: True
  fairdata-test-accounts-users:
    external: True
  fairdata-test-accounts-credentials:
    external: True
  fairdata-test-accounts-initialize:
    external: True