#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------

# This script generates diffs for all of the modified files in the old nextcloud,
# detailing what has been modified from the originals, placing them in the
# subdirectory ./diffs-old-modified/.

source ../config/config.sh

OPTS="-u --ignore-all-space --ignore-blank-lines"

for PATHNAME in `./list-new-modified-files`; do
    DIRS=`dirname "${PATHNAME}"`
    mkdir -p "./diffs/diffs-new-modified${DIRS}"
    diff $OPTS "${PATHNAME}" "${PATHNAME}.original" > "./diffs/diffs-new-modified${PATHNAME}.diff" 
done

