#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------

# This script generates diffs for all of the modified files in the old nextcloud,
# compared to the same files, if any, in the new nextcloud, indicating where and
# how the new files differ from the latest modified versions in the old nextcloud,
# saving the diffs in the subdirectory ./diffs-old-new/. No diff file is created
# if the file doesn't exist in the new nextcloud.

source ../config/config.sh

OPTS="-u --ignore-all-space --ignore-blank-lines"

for PATHNAME in `./list-modified-files`; do
    OLDPATHNAME=`echo "${PATHNAME}" | sed -e 's/nextcloud/nextcloud-old/'`
    NEWPATHNAME=`echo "${PATHNAME}" | sed -e 's/nextcloud/nextcloud-new/'`
    if [ -s "${NEWPATHNAME}" ]; then
        DIRS=`dirname "${PATHNAME}"`
        mkdir -p "./diffs-old-new${DIRS}"
        diff $OPTS "${NEWPATHNAME}" "${OLDPATHNAME}" > "./diffs-old-new${PATHNAME}.diff" 
    fi
done


