#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------
. `dirname $0`/../lib/init_script.sh

USAGE="Usage: $SCRIPT user_name"

# checks

if [ $# -ne 1 ]; then
	errorExit "$USAGE"
fi

USER="$1"

# execute

if [ "$OC_PASS" = "" ]; then
	errorExit "No new password, OC_PASS is empty, user: $USER"
fi
OUT=`php "$OCC" user:resetpassword --password-from-env "$USER" 2>&1`
HITS=`echo $OUT | grep 'Successfully reset password' | wc -l`
if [ "$HITS" -ne 1 ]; then
	errorExit "$OUT"
fi

