#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------

source ../config/config.sh

if [ "$RABBIT_VHOST" = "" -o "$RABBIT_ADMIN_USER" = "" -o "$RABBIT_WORKER_USER" = "" -o "$RABBIT_MONITOR_USER" = "" ]; then
	echo "Missing config value"
	exit 1
fi

rabbitmqctl add_user "$RABBIT_ADMIN_USER" "$RABBIT_ADMIN_PASS"
rabbitmqctl add_user "$RABBIT_WORKER_USER" "$RABBIT_WORKER_PASS"
rabbitmqctl add_user "$RABBIT_MONITOR_USER" "$RABBIT_MONITOR_PASS"

rabbitmqctl set_permissions "$RABBIT_ADMIN_USER" '.*' '.*' '.*'

rabbitmqctl add_vhost "$RABBIT_VHOST"

rabbitmqctl set_permissions -p "$RABBIT_VHOST" "$RABBIT_WORKER_USER" '^$' '.*' '.*'
rabbitmqctl set_permissions -p "$RABBIT_VHOST" "$RABBIT_MONITOR_USER" '^$' '^$' '.*'

rabbitmqctl delete_user guest

rabbitmqctl set_user_tags "$RABBIT_ADMIN_USER" administrator
rabbitmqctl set_user_tags "$RABBIT_WORKER_USER" management
rabbitmqctl set_user_tags "$RABBIT_MONITOR_USER" management

