#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------
. `dirname $0`/../lib/init_script.sh

if [ "$IDA_ENVIRONMENT" != "TEST" ]; then
    errorExit "This script can only be run in a test environment. Aborting."
fi

export OC_PASS="test"

#--------------------------------------------------------------------------------
# Input integrity checks

PROJECT_NAME=$1

if [ -z "$PROJECT_NAME" ]; then
    errorExit "Empty project name."
fi

# Generate PSO user name from project name
PROJECT_USER="$PROJECT_USER_PREFIX""$PROJECT_NAME"

# Update Nextcloud filesystem to reflect all back-end changes
$OCC files:scan -q $PROJECT_USER
$OCC files:cleanup 

