#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------
. `dirname $0`/../lib/init_script.sh

#--------------------------------------------------------------------------------
# Set every project share owner account password to the current PROJECT_USER_PASS
# value currently defined in the local configuration. This script takes no args.
#--------------------------------------------------------------------------------

# checks

export OC_PASS=$PROJECT_USER_PASS

# execute

echo "Resetting project share owner account passwords to \"$OC_PASS\" ..."

# Get all project user account names

PROJECT_USERS=`cd "$STORAGE_OC_DATA_ROOT"; ls | egrep -e "^$PROJECT_USER_PREFIX" | sed -e 's/[\s\@]+/ /g'`

for PROJECT_USER in $PROJECT_USERS; do
    # Derive project name and check for project staging share folder, to skip any
    # inactive/residue PSO users...
    PROJECT_NAME=`echo $PROJECT_USER | sed -e "s/^$PROJECT_USER_PREFIX//"`
    if [ -e $STORAGE_OC_DATA_ROOT/$PROJECT_USER/files/$PROJECT_NAME ]; then
        php "$OCC" user:resetpassword --password-from-env "$PROJECT_USER"
    fi
done

