#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
#--------------------------------------------------------------------------------
. `dirname $0`/../lib/init_script.sh

#--------------------------------------------------------------------------------
# Set the admin account password to the current NC_ADMIN_PASS value currently
# defined in the local configuration. This script takes no args.
#--------------------------------------------------------------------------------

# checks

export OC_PASS=$NC_ADMIN_PASS

# execute

echo "Resetting $NC_ADMIN_USER account password to \"$OC_PASS\" ..."

php "$OCC" user:resetpassword --password-from-env "$NC_ADMIN_USER"

