#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the IDA research data storage service
#
# Copyright (C) 2020 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://research.csc.fi/
# --------------------------------------------------------------------------------

SCRIPT_PATHNAME="$(realpath $0)"
PARENT_FOLDER=`dirname "$SCRIPT_PATHNAME"`
PARENT_BASENAME=`basename "$PARENT_FOLDER"`

while [ "$PARENT_BASENAME" != "ida" -a "$PARENT_BASENAME" != "" ]; do
    PARENT_FOLDER=`dirname "$PARENT_FOLDER"`
    PARENT_BASENAME=`basename "$PARENT_FOLDER"`
done

CONFIG_FILE="$PARENT_FOLDER/config/config.sh"

if [ -e $CONFIG_FILE ]
then
    . $CONFIG_FILE
else
    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

ID=`id -u -n`
if [ "$ID" != "root" ]; then
    echo "You must execute this script as root"
    exit 1
fi

if [ ! -x $PYTHON ]; then
    echo "$PYTHON does not exist!" >&2
    exit 1
fi

if [ "$VENV_TESTS" = "" ]; then
    echo "Virtual environment path not defined in configuration!" >&2
    exit 1
fi

rm -fr $VENV_TESTS

$PYTHON -m venv $VENV_TESTS

source $VENV_TESTS/bin/activate

pip install --upgrade pip
pip install -r $ROOT/tests/requirements.txt

chown -R $HTTPD_USER:$HTTPD_USER $VENV_TESTS
chmod -R g+rwX $VENV_TESTS

